name: AWS Infrastructure Setup
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  setup-network-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      vpc-id: ${{ steps.set-outputs.outputs.VPC_ID }}
      subnet-ids: ${{ steps.set-outputs.outputs.SUBNET_IDS }}
      security-group-id: ${{ steps.set-outputs.outputs.SG_ID }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create VPC
        id: create-vpc
        run: |
          VPC_ID=$(aws ec2 create-vpc --cidr-block 10.0.0.0/16 --query 'Vpc.VpcId' --output text)
          aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames
          echo "VPC_ID=$VPC_ID" >> $GITHUB_OUTPUT

      - name: Create Internet Gateway
        id: create-igw
        run: |
          IGW_ID=$(aws ec2 create-internet-gateway --query 'InternetGateway.InternetGatewayId' --output text)
          echo "IGW_ID=$IGW_ID" >> $GITHUB_OUTPUT
          aws ec2 attach-internet-gateway --vpc-id ${{ steps.create-vpc.outputs.VPC_ID }} --internet-gateway-id $IGW_ID

      - name: Create Subnets
        id: create-subnets
        run: |
          SUBNET1_ID=$(aws ec2 create-subnet \
            --vpc-id ${{ steps.create-vpc.outputs.VPC_ID }} \
            --cidr-block 10.0.1.0/24 \
            --availability-zone ${AWS_REGION}a \
            --query 'Subnet.SubnetId' --output text)
          
          SUBNET2_ID=$(aws ec2 create-subnet \
            --vpc-id ${{ steps.create-vpc.outputs.VPC_ID }} \
            --cidr-block 10.0.2.0/24 \
            --availability-zone ${AWS_REGION}b \
            --query 'Subnet.SubnetId' --output text)
          
          echo "SUBNET_IDS=$SUBNET1_ID,$SUBNET2_ID" >> $GITHUB_OUTPUT

      - name: Create Route Table
        id: create-route-table
        run: |
          ROUTE_TABLE_ID=$(aws ec2 create-route-table --vpc-id ${{ steps.create-vpc.outputs.VPC_ID }} --query 'RouteTable.RouteTableId' --output text)
          aws ec2 create-route --route-table-id $ROUTE_TABLE_ID --destination-cidr-block 0.0.0.0/0 --gateway-id ${{ steps.create-igw.outputs.IGW_ID }}
          aws ec2 associate-route-table --route-table-id $ROUTE_TABLE_ID --subnet-id ${{ steps.create-subnets.outputs.SUBNET1_ID }}
          aws ec2 associate-route-table --route-table-id $ROUTE_TABLE_ID --subnet-id ${{ steps.create-subnets.outputs.SUBNET2_ID }}

      - name: Create Security Group
        id: create-sg
        run: |
          SG_ID=$(aws ec2 create-security-group \
            --group-name Beanstock-Postgres-SG \
            --description "Security group for PostgreSQL" \
            --vpc-id ${{ steps.create-vpc.outputs.VPC_ID }} \
            --query 'GroupId' --output text)
          
          # Allow PostgreSQL access
          aws ec2 authorize-security-group-ingress \
            --group-id $SG_ID \
            --protocol tcp \
            --port 5432 \
            --cidr 0.0.0.0/0
          
          echo "SG_ID=$SG_ID" >> $GITHUB_OUTPUT

      - name: Set Outputs
        id: set-outputs
        run: |
          echo "VPC_ID=${{ steps.create-vpc.outputs.VPC_ID }}" >> $GITHUB_OUTPUT
          echo "SUBNET_IDS=${{ steps.create-subnets.outputs.SUBNET_IDS }}" >> $GITHUB_OUTPUT
          echo "SG_ID=${{ steps.create-sg.outputs.SG_ID }}" >> $GITHUB_OUTPUT
